name: Checkstyle and PMD Analysis
on:
  pull_request:
    branches: [pmd_debug] # Changed branch name to pmd_debug
  push:
    branches: [main] # Changed branch name to main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Run Checkstyle
        run: |
          mvn clean checkstyle:checkstyle

      - name: Set up Maven for PMD
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Download PMD
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases/6.55.0/pmd-bin-6.55.0.zip
          unzip pmd-bin-6.55.0.zip
          mv pmd-bin-6.55.0 pmd

      - name: Create Custom PMD Ruleset
        run: |
          cat <<EOF > custom-pmd-ruleset.xml
          <?xml version="1.0"?>
          <ruleset name="Custom PMD Ruleset"
              xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/xsd/ruleset_2_0_0.xsd">
            <description>Custom PMD ruleset to ignore ShortVariable and LongVariable rule.</description>

            <rule ref="rulesets/java/basic.xml"/>
            <rule ref="rulesets/java/empty.xml"/>
            <rule ref="rulesets/java/imports.xml"/>
            <rule ref="rulesets/java/unnecessary.xml"/>
            <rule ref="rulesets/java/design.xml"/>

            <rule ref="rulesets/java/naming.xml">
                <exclude name="ShortVariable"/>
                <exclude name="LongVariable"/>
            </rule>

            <rule ref="rulesets/java/unusedcode.xml"/>
          </ruleset>
          EOF

      - name: Run PMD Analysis
        id: pmd-analysis
        run: ./pmd/bin/run.sh pmd -d src/main/java -f text -R custom-pmd-ruleset.xml

      - name: Fail if PMD violations are found
        if: steps.pmd-analysis.outcome == 'failure'
        run: exit 1

  test: # Added a test job.  This was missing.
    name: Test Debug Variant # Added a name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Run Tests
        run: mvn test # Basic test command.  Adjust as needed.
